site_name: xiaoxuan6's 周刊
site_author: xiaoxuan6

repo_name: xiaoxuan6/weekly
repo_url: https://github.com/xiaoxuan6/weekly

extra_javascript:
  - https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
  - static/js/index.js

extra:
  social:
    - icon: fontawesome/solid/blog
      link: https://xiaoxuan6.github.io
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xiaoxuan6

theme:
  name: material
  features: # https://squidfunk.github.io/mkdocs-material/setup/
    - navigation.instant # 进度指示器
    - navigation.instant.progress
    - navigation.tracking # 锚点追踪
    - content.code.annotate # 代码注释
    - content.code.copy # 代码复制按钮
    # - navigation.expand # 导航扩展 - 启用扩展后，左侧边栏将默认展开所有可折叠的子部分
    - navigation.sections # 左侧目录滚动条
    - navigation.top # 返回顶部按钮
    - toc.integrate # 目录导航整合
    - toc.follow
    - navigation.tracking # 锚点追踪
    - search.highlight # 搜索突出显示
    - search.share # 搜索分享
    - search.suggest # 搜索建议 - 启用搜索建议后，搜索将显示可通过按键接受的最后一个单词的最可能的补全Right
  language: zh
  palette:
    - accent: black
      primary: black
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - accent: indigo
      primary: white
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  search_index_only: true

plugins:
  - search
  - git-revision-date-localized

nav:
  - 第1期: ./第1期.md

copyright: Copyright &copy; 2023 <a href="https://github.com/xiaoxuan6/weekly">xiaoxuan6's</a>.
