name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: "pip"
      - run: |
          pip install pip -U
          pip install -r requirements.txt
          mkdocs gh-deploy --force