name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'build.yml'
      - 'docs/static/js/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: "pip"
      - run: |
          pip install pip -U
          pip install -r requirements.txt
          filenames=$(git log -1 --name-status --pretty=format:"" | cut -f 2-)
          if [[ $filenames =~ 第[0-9]+期|mkdocs.yml|build.yml ]]; then
            mkdocs build
            mkdocs gh-deploy --clean
            echo "build successful!"
          else
            echo "no build"
          fi
