name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: "pip"
      - run: |
          pip install pip -U
          pip install -r requirements.txt
          filenames=$(git log -1 --name-status --pretty=format:"" | cut -f 2-)
          if [[ $filenames =~ 第[0-9]+期 ]]; then
            mkdocs gh-deploy --force
          fi