name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: "pip"
      - run: |
          pip install pip -U
          pip install -r requirements.txt
          filenames=$(git log -1 --name-status --pretty=format:"" | cut -f 2-)
          if [[ $filenames =~ 第[0-9]+期|mkdocs.yml ]]; then
            make build
            echo "build successful!"
          else
            echo "no build"
          fi
        working-directory: /home/runner/work/weekly/weekly