name: Auto merge pr

on:
  pull_request:
    types:
      - created

jobs:
  mrege:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: merge pr
        run: |
          if [ "${{ github.event.pull_request.user.login }}" == "ImgBot" ]; then
            # 在这里执行合并操作
            gh pr merge "${{ github.event.pull_request.number }}" --delete-branch
          else
            echo "Author is not ImgBot, skipping merge."
          fi